version: '3.8'

services:
  matchmaker:
    build: .
    ports:
      - "3000:3000"
      - "7000-7100:7000-7100"
    volumes:
      - ./src:/app/src
      - ./game_build:/app/game_build
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    platform: linux/x86_64
